### ISSUE TITLE
make everything smaller and more compact

### ISSUE THREAD

**Issue by mokit** [wieni/wienimal#1]
see **raw** preview below
![screencapture-flandersliterature-wieni-work-admin-content-1484753303636](https://cloud.githubusercontent.com/assets/344372/22461299/fee87156-e7a8-11e6-90ba-34a68a3f5851.png)

**Comment by sqndr** [comment]
This has been done.

**Comment by sqndr** [comment]
@mokit Ready to be reviewed.

**Comment by sqndr** [comment]
Closing for now.
