### ISSUE TITLE
Radio Boxes

### ISSUE THREAD

**Issue by brownrl** [wieni/wienimal#12]
Radio Boxes do not get the nice theming.

![screen shot 2017-02-27 at 13 41 32](https://cloud.githubusercontent.com/assets/3533399/23361757/871e27a6-fcf2-11e6-9991-4815df6eaeb9.png)

**Comment by sqndr** [comment]
Since we're rending the styling is correct … this is what we want a fieldset to look like inside a tab. It works fine when not placed inside a tab.
