### ISSUE TITLE
Operations dropdown remove ?destination parameter

### ISSUE THREAD

**Issue by spoit** [wieni/wienimal#4]
## Problem/Motivation

Inside the `links--dropbutton.html.twig` the attributes of the links are gone, due to the fact that the link is manually printed:

```
{{ link(links|first.link['#title'], links|first.link['#url'], { 'class': link_classes }) }}
```

## Proposed solution

Just print the `link` and fix the styles in the **css**.

## Original report by @spoit:
eg on admin/content the edit link points to:

`/node/1/edit?destination=/admin/content`

but it should point to:

`/node/1/edit?destination=/admin/content`

When I switch the admin theme to Seven the link is correct so it is 'something' in the wienimal theme that removes these

**Comment by sqndr** [comment]
Done.
