### ISSUE TITLE
Bewerkingslink heeft geen destination query param

### ISSUE THREAD

**Issue by RobinHoutevelts** [wieni/wienimal#5]
<h3 id="summary-problem-motivation">Problem/Motivation</h3>
Bewerkingslink verliest <code>?destination=</code> query param. 

<h3 id="summary-proposed-resolution">Proposed resolution</h3>
Sander fixt da met wizard magic

<h3 id="summary-remaining-tasks">Remaining tasks</h3>
[ ] Fix

<h3 id="summary-ui-changes">User interface changes</h3>
None

<h3 id="summary-api-changes">API changes</h3>
None

<h3 id="summary-data-model-changes">Data model changes</h3>
None

**Comment by sqndr** [comment]
See #4
